### PR TITLE
Start using TypeScript

### PR DESCRIPTION
**Pull request by jameshadfield**
### Description of proposed changes    

Adds basic TypeScript support and conversion of a few files into TS/TSX.

See commit messages.

### CODE REVIEW

File: .eslintrc [hunk 1]
```diff
@@ -38,7 +38,7 @@ rules:
   class-methods-use-this: off
   react/jsx-tag-spacing: ["error", { "closingSlash": "never", "beforeSelfClosing": "allow", "afterOpening": "never" }]
   react/forbid-prop-types: off
-  react/jsx-filename-extension: [1, { "extensions": [".js", ".jsx"] }]
+  react/jsx-filename-extension: [1, { "extensions": [".js", ".jsx", ".ts", ".tsx"] }]
```
Comment (tsibley) [inline .eslintrc:41]: This addition should probably be part of the previous commit (bbbc054990481613b441f2690d0657d5494cfea2) and not lumped in with the example TypeScript so it's retained instead of dropped before merge.

Comment (jameshadfield) [reply .eslintrc:41]: Thanks - changed!

For what it's worth, I think the first commit is still incomplete and will need some webpack config / ts config etc changes to get it working smoothly.

**Comment by ivan-aksamentov** [comment]
I thought you'd just delete the types when porting the badges, but you decided to add Typescript to auspice instead :) 

Looks good! Mild concern only that in package.json typings do not correspond to the versions of js packages (e.g. react and styled-components are a major version ahead), which may make type checking and text editor assist less useful and even harmful. Otherwise I am super jazzed about auspice getting some types!

File: src/util/tipRadiusHelpers.ts [hunk 2]
```diff
@@ -44,13 +47,16 @@ const determineLocationMatch = (node, geoResolution, geoValueToMatch) => {
...
-export const calcTipRadii = ({tipSelectedIdx = false, selectedLegendItem = false, geoFilter = [], searchNodes = false, colorScale, tree}) => {
+export const calcTipRadii = (
+  {tipSelectedIdx = false, selectedLegendItem = false, geoFilter = [], searchNodes = false, colorScale, tree}:
+  {tipSelectedIdx:(number|false), selectedLegendItem:(number|string|false), geoFilter:([string, string]|[]), searchNodes:any, colorScale:any, tree:any}
+) => {
   if (selectedLegendItem !== false && tree && tree.nodes) {
-    return tree.nodes.map((d) => determineLegendMatch(selectedLegendItem, d, colorScale) ? tipRadiusOnLegendMatch : tipRadius);
+    return tree.nodes.map((d:any) => determineLegendMatch(selectedLegendItem, d, colorScale) ? tipRadiusOnLegendMatch : tipRadius);
   } else if (geoFilter.length===2 && tree && tree.nodes) {
-    return tree.nodes.map((d) => determineLocationMatch(d, ...geoFilter) ? tipRadiusOnLegendMatch : tipRadius);
```
Comment (jameshadfield) [inline src/util/tipRadiusHelpers.ts:51]: I was surprised TS didn't allow `...geoFilter` given that the preceding `if` statement ensures there are 2 elements. Perhaps three's some gotchas in the spread operator that I don't understand.

Comment (ivan-aksamentov) [reply src/util/tipRadiusHelpers.ts:51]: Compiled languages rarely check array lengths[1], because it often requires runtime information, while compilers only have information available at compile time. In this particular case, it might be possible to prove that array size is 2, but in many cases it's not.

I'd say, this code is questionable. If `geoFilter` always has two items, then why it's not an object with named fields. They are even given names inside `determineLocationMatch()`. 

It looks like an abuse of container type. I guess it can also be empty (parameter is defaulted to `[]`)? Can it be anything else? 1 element? How about 3? Long story short, is'a a bit of a sloppy, indecisive code, because it does not know what it wants. 

Typescript does not make it easy to write code where things constantly transmute - an elephant becomes a banana and then in another file it becomes a space ship. Typescript requires some discipline. It puts constraints onto the Wild West of JS, and tries to make code less dynamic and easier to reason about.


Ideally I'd write something like:

```typescript
// TODO: prehaps rename fields to have less of repeated "geo" prefix
export interface GeoFilters {
  geoResolution: string;
  geoValueToMatch: string;
}

function calcTipRadii(
  // ... more params
  geoFilters?: GeoFilters // can be `undefined`
  // ... more params
) {
  // ...
  if (geoFilters) {
    return determineLocationMatch(node, geoFilters)
  }
  // ...
}

function determineLocationMatch(
  node: Node,
  { geoResolution, geoValueToMatch }: GeoFilters // destructuring
) {
  return geoValueToMatch === getTraitFromNode(node, geoResolution);
}

```


If you really want to abuse the container type (e.g. because it comes from a stable file format, and you don't want to write additional conversions), then in Typescript there's a [tuple](https://www.typescriptlang.org/docs/handbook/2/objects.html#tuple-types) type, which can emulate fixed-size array. You could make `geoTypes` of type `[string, string]`, which is different from `string[]`. But in this particular code `geoTypes` defaults to `[]`, and `[]` cannot be of type `[string, string]`. So it needs additional re-thinking.


--

[1] One exception is Rust, where you have separate [`Vec`](https://doc.rust-lang.org/std/vec/struct.Vec.html) type for dynamic arrays and [array](https://doc.rust-lang.org/std/primitive.array.html) type `[i32;N]` for fixed-size arrays. The `N` in the array type is then a part of the type, and is checked on compile-time, while `Vec` is only checked at runtime.

**Comment by ivan-aksamentov** [comment]
I just realized I have a bunch of typings written for Aupice in Nextclade. These are just the things that are used in Nextcade, so many things may be missing or inaccurate

https://github.com/nextstrain/nextclade/tree/master/packages_rs/nextclade-web/src/types/auspice

and the tree type is for some reason in a separate place:

File: src/util/getGenotype.js [hunk 3]
```diff
@@ -20,6 +20,13 @@ export const encodeColorByGenotype = ({ gene, positions }) => {
...
+export const decodePositions = (positions, geneLength = 'Infinity') => {
+  return positions
+    .split(",")
+    .map((x) => parseInt(x, 10))
+    .filter((x) => x > 0 && x <= Math.floor(geneLength));
+};
+
 /* Examples:
  *   gt-nuc_142       → { gene: "nuc", aa: false, positions: [142] }
  *   gt-nuc_142,144   → { gene: "nuc", aa: false, positions: [142,144] }
```
Comment (tsibley) [inline src/util/getGenotype.js:32]: > These weren't flagged as errors previously, however the previous commit swapped the rule "no-use-before-define" to "@typescript/no-use-before-define".
> […]
> I don't know enough about specifications to know why this is considered an error but still works in practice, however it's not much effort to reorganise the code in these 2 files.

I find this sort of reorganization actively harmful to the ability to read the code in a file. Reading top to bottom, I want to read the higher level functions first, which call the lower level functions that I'll read next. The opposite is like putting the cart before the horse. `decodePositions` is out of context and makes no sense until I see it called in `decodeColorByGenotype`.

This is why in Auspice 6f22d9f87e3e8e16662a1717b527d2351fe44ff1 disabled `no-use-before-define` for functions, based on [my change to nextstrain.org's config](https://github.com/nextstrain/nextstrain.org/commit/fc4aee33db580dbe0a76529f19137e24b8ce31c4).

Comment (jameshadfield) [reply src/util/getGenotype.js:32]: There's a few things at play here.

Firstly, I didn't notice the existing eslint overrule for that line [1]:

https://github.com/nextstrain/auspice/blob/b58f14889924ca887587d5a65d623b97d0ed1b32/src/util/getGenotype.js#L45

With this PR this overrule needs to change to `// eslint-disable-line @typescript-eslint/no-use-before-define`, which I'll do as part of this PR. (This keeps the code as intended, which is appropriate for this PR.)


Secondly, I don't know why the following change was made (by me, but over a year ago):

```diff
-  no-use-before-define: ["error", { "functions": false }]
+  no-use-before-define: "off"  # note you must disable the base rule as it can report incorrect errors
+  "@typescript-eslint/no-use-before-define": ["error", { "functions": false }]
```

The intention is to allow function (not fat-arrow) hoisting as per https://github.com/nextstrain/auspice/commit/6f22d9f87e3e8e16662a1717b527d2351fe44ff1 (rule docs [here](https://eslint.org/docs/latest/rules/no-use-before-define#functions)). Linting behavior under `no-use-before-define": ["error", { "functions": false }]`:

```
# Not valid JS, and has linting errors
const foo = () => bar();
foo();
const bar = () => {console.log("42");};

# Valid JS, and no linting errors
const foo = () => bar();
foo();
function bar() {console.log("42");}

# Valid JS, but linting fails because of the introduction
# of a temporal dead zone. Allowable by using
# ["error", { "functions": false, "variables": false}]
const foo = () => bar();
const bar = () => {console.log("42");};
foo();
```

The third example is why we get the errors in `choose-layout.js`, however why they were flagged up now and not before I don't understand 🤷 . Note that while setting `"variables": false` allows the existing code in `choose-layout.js` it also allows the first toy example above to pass linting, despite it throwing a `ReferenceError` when run. 

[1] You wrote that override a ~year before we allowed function hoisting in https://github.com/nextstrain/auspice/commit/6f22d9f87e3e8e16662a1717b527d2351fe44ff, but it's not a function declaration so it wouldn't be affected by that rule anyways.

File: src/util/tipRadiusHelpers.ts (hunk 2 above)
Comment (jameshadfield) [reply src/util/tipRadiusHelpers.ts:51]: Thanks @ivan-aksamentov - since TS [allows conditional statements to narrow the types](https://www.typescriptlang.org/docs/handbook/2/narrowing.html) I expected this to be ok; perhaps it doesn't like it because we may have overriden the `length` prototype?

And fully agree with your general comments about the code -- this is one of the reasons I want to mostly write things in TS going forward (as well as the implicit documentation it'll provide when reading/writing code). However I didn't want to labour this PR with code changes, I just tried to find the most self-contained file to port to TS I could.

**Comment by jameshadfield** [comment]
Aside from the threaded discussions happening above, how do we feel about merging this PR? Specifically @ivan-aksamentov, @tsibley, @joverlee521 and @victorlin - but I welcome anyone else's thoughts as well! I either want to discard this PR or merge it (with appropriate fixes), not leave it hanging for another year!

File: src/util/tipRadiusHelpers.ts (hunk 2 above)
Comment (jameshadfield) [reply src/util/tipRadiusHelpers.ts:51]: Interestingly, changing the type from `geoFilter:([string, string]|[])` to `geoFilter?:[string, string]` (and therefore using `undefined` for the default argument) _does_ allow the spread operator to be used. I'm not going to make this change in this PR as there's other files which call this function using an empty array argument, but it was an interesting insight into how TS works. 

```diff
 export const calcTipRadii = (
-  {tipSelectedIdx = false, selectedLegendItem = false, geoFilter = [], searchNodes = false, colorScale, tree}:
-  {tipSelectedIdx:(number|false), selectedLegendItem:(number|string|false), geoFilter:([string, string]|[]), searchNodes:any, colorScale:any, tree:any}
+  {tipSelectedIdx = false, selectedLegendItem = false, geoFilter = undefined, searchNodes = false, colorScale, tree}:
+  {tipSelectedIdx:(number|false), selectedLegendItem:(number|string|false), geoFilter?:[string, string], searchNodes:any, colorScale:any, tree:any}
 ) => {
   if (selectedLegendItem !== false && tree && tree.nodes) {
     return tree.nodes.map((d:any) => determineLegendMatch(selectedLegendItem, d, colorScale) ? tipRadiusOnLegendMatch : tipRadius);
-  } else if (geoFilter.length===2 && tree && tree.nodes) {
-    return tree.nodes.map((d:any) => determineLocationMatch(d, geoFilter[0], geoFilter[1]) ? tipRadiusOnLegendMatch : tipRadius);
+  } else if (geoFilter?.length===2 && tree && tree.nodes) {
+    return tree.nodes.map((d:any) => determineLocationMatch(d, ...geoFilter) ? tipRadi
usOnLegendMatch : tipRadius);
   } else if (searchNodes) {
     return tree.nodes.map((d:any) => d.name.toLowerCase().includes(searchNodes) ? tipR
adiusOnLegendMatch : tipRadius);
   } else if (tipSelectedIdx) {
```

File: src/util/getGenotype.js (hunk 3 above)
Comment (tsibley) [reply src/util/getGenotype.js:32]: Compared ASTs for this toy example:

```js
class Foo extends React.Component {
  renderX() {
    return (<Bar />);
  }
}

const Bar = ({ }) => (<>bar</>);
```

using https://astexplorer.net with `@babel/eslint-parser` and `@typescript-eslint/parser`. Sorting the JSON output and [diffing it](https://gist.github.com/tsibley/06761e22bff4fdc812a348b1871e3dd7) produces nothing obvious. It's very similar. So maybe Typescript's `no-use-before-define` rule supports `JSXIdentifier` nodes and the standard rule just… doesn't?

OTOH, signs still point to a parsing difference when I interrogate the example above with `npx eslint --ext .js,.ts,.jsx,.tsx --parser @babel/eslint-parser` vs. `… --parser @typescript-eslint/parser` and also try switching between the two rules.

parser / rule | `no-use-before-define` | `@typescript-eslint/no-use-before-define`
--- | --- | ---
`@babel/eslint-parser` | ok | ok
`@typescript-eslint/parser` | ok | errors

**Review by tsibley — APPROVED** [review]
Happy to see this merged. Good to get Typescript support going!

(Would be good to resolve the outstanding threads and minor fixes before merging.)

**Comment by ivan-aksamentov** [comment]
I think typescript-eslint is not configured correctly, the "extends" clause is missing:
https://typescript-eslint.io/getting-started

My current understanding is as follows: some of the eslint rules are also in typescript-eslint, but adapted for typescript. In case  of eslint rule needs to be disabled - this is what the extends clause is doing - it "pastes" config for some of the rules.

There are also additional rules that use type information:
https://typescript-eslint.io/linting/configs

File: tsconfig.json [hunk 4]
```diff
@@ -0,0 +1,101 @@
...
+    // "noFallthroughCasesInSwitch": true,               /* Enable error reporting for fallthrough cases in switch statements. */
+    // "noUncheckedIndexedAccess": true,                 /* Include 'undefined' in index signature results */
+    // "noImplicitOverride": true,                       /* Ensure overriding members in derived classes are marked with an override modifier. */
+    // "noPropertyAccessFromIndexSignature": true,       /* Enforces using indexed accessors for keys declared using an indexed type */
+    // "allowUnusedLabels": true,                        /* Disable error reporting for unused labels. */
+    // "allowUnreachableCode": true,                     /* Disable error reporting for unreachable code. */
+
+    /* Completeness */
+    // "skipDefaultLibCheck": true,                      /* Skip type checking .d.ts files that are included with TypeScript. */
+    "skipLibCheck": true                                 /* Skip type checking all .d.ts files. */
```
[the remark this answers is not in the document]
Comment (jameshadfield) [reply tsconfig.json:99]: I'll go through these rules in a bit more depth as part of this PR - I just wanted to get confirmation that we were happy with the TS direction before sinking time into things like this.

[the remark this answers is not in the document]
Comment (victorlin) [reply tsconfig.json]: I pushed ad612cb1b1a13e381da666bdc029d1a3ca9fb834 to address this.

@jameshadfield I can go through the rest of these if you haven't started doing so yet.

[the remark this answers is not in the document]
Comment (jameshadfield) [reply tsconfig.json]: Yeah that'd be great - thanks @victorlin. It'd also be a good idea to convert a file over to TS which uses 3rd party libraries (i.e. `import @types/abc`) so we can make sure that works. 

P.S. Thanks for the detailed commit message! 💯

File: package.json [hunk 5]
```diff
@@ -21,8 +21,10 @@
     "server": "npm run view",
     "build": "node auspice.js build --verbose",
     "prepare": "npm run build",
-    "lint": "eslint src",
+    "lint": "eslint src --ext .js,.ts,.jsx,.tsx",
     "lint:fix": "eslint --fix src",
+    "type-check": "tsc --noEmit",
```
[the remark this answers is not in the document]
Comment (jameshadfield) [reply package.json:26]: Yeah, I implemented it that way [following these recommendations](https://www.typescriptlang.org/docs/handbook/babel-with-typescript.html#babel-for-transpiling-tsc-for-types). (That link also has some tips regarding the TS config which may be useful.)

Our babel setup has been with us for a long time, and it's very possible that there's an improved way of doing things now, but for this PR I tried to make minimal changes to this setup. If you want to make broader changes go for it! (Although perhaps in a different PR?)

[the remark this answers is not in the document]
Comment (victorlin) [reply package.json:26]: That makes sense! Just wanted to clarify since it determines which config options to use.

[the remark this answers is not in the document]
Comment (jameshadfield) [reply package.json:26]: Great. It'd be interesting to talk through this with you after you're done to better gauge what work would be involved with moving to a TS compiler, and what the benefits/disadvantages are. There are a bunch of moving parts (webpack, babel, tsc, dozens of plugins) and auspice allows users to re-build the client with customisations; this made me hesitant to dive into it for this PR.

**Comment by victorlin** [comment]
I've [updated](https://github.com/nextstrain/auspice/compare/ad612cb1b1a13e381da666bdc029d1a3ca9fb834..5ce2ed1f9acf3f510c1c75a9a98967958df3fe50) this PR with improvements to webpack/ESLint/TS configs and converted a couple more files over to TS. This PR should be re-reviewed.

File: tsconfig.json (hunk 4 above)
[the remark this answers is not in the document]
Comment (victorlin) [reply tsconfig.json]: [Done](https://github.com/nextstrain/auspice/pull/1450#issuecomment-1507765006).

**Comment by ivan-aksamentov** [comment]
@victorlin IMO typescript-eslint is still not configured correctly, as I mentioned above. The `extends` clause is missing:
https://typescript-eslint.io/getting-started
That's why you guys have all these weird pink elephants. Or at least some of them.

**Comment by victorlin** [comment]
@ivan-aksamentov I don't think extending `plugin:@typescript-eslint/recommended` is necessary. We are already extending `airbnb` which is another set of recommended config presets, and `airbnb-typescript` (added in 9b0c47f33159816c19358d7b54c735491ace2f15) [has the same rule override](https://github.com/iamturns/eslint-config-airbnb-typescript/blob/91fd090f6fdd8d598a6ac6e9bb2c2ba33014e425/lib/shared.js#L185-L188) as the configuration you linked.

Regardless, I tried: extended `plugin:@typescript-eslint/recommended` and reverted 9cab2aa4042966a958311833ce16f0fbc089bb02, still got the same `no-use-before-define` errors. @tsibley's [digging](https://github.com/nextstrain/auspice/pull/1450#discussion_r1154812873) might be the closest explanation that we have right now.

**Comment by victorlin** [comment]
Rebased onto new changes from #1665. Summary of what's new:

- Dropped 9b0c47f: goodbye Airbnb base config
- Replaced c73b271 with aeb77bc5: hello new base configs
- Added af4c742f...b09d0968: add another `recommended` base config
- Replaced 9cab2aa with af4c742f: it was partially addressed by 9fc42f01
- Dropped the addition of `import/extensions` in c73b271c: [this was only necessary with Airbnb base config](https://stackoverflow.com/a/59268871)

File: src/util/getGenotype.js (hunk 3 above)
Comment (jameshadfield) [reply src/util/getGenotype.js]: Nice work going down that rabbit hole!

As part of PR #1665, https://github.com/nextstrain/auspice/commit/9fc42f01ee6609631a9d864da7e8c4da5cf5e583 turned `decodePositions` into a function declaration which is hoisted:

```diff
- export const decodePositions = (positions, geneLength = 'Infinity') => {
+ export function decodePositions(positions, geneLength = 'Infinity') {
```
This is left unchanged by this PR.

The changes to `choose-layout.js` still remain in this PR, due to the change in interpretation between `@babel/eslint-parser` and `@typescript-eslint/parser` (as per Tom's message above).

I think this thread can be considered resolved.

The other cha

**Review by jameshadfield — COMMENTED** [review]
Awesome work @victorlin! I had only one suggestion and one question after reading through the commits and testing it out locally. Excited to get this merged 😄 

This PR accomplishes exactly what I envisioned -- we get the benefits of TS support, without needing to overhaul the rather complex webpack configuration we have. Thanks for finishing it up!

I triggered PRs for nextstrain.org & auspice.us. The former passed CI but failed docs building ([logs](https://readthedocs.org/projects/nextstrainorg/builds/20534311/)) - probably unrelated? I manually built auspice.us and it worked as expected.

P.S. The `tsconfig.json` I introduced in cb6bd9f76a1f75fe16b70a19057b1b7f5dc418f5 with most options commented out was auto-generated by `tsc -init`, in case that wasn't clear!

File: package.json [hunk 6]
```diff
@@ -123,6 +123,7 @@
     "yaml-front-matter": "^4.0.0"
   },
   "devDependencies": {
+    "@types/leaflet": "^1.9.3",
```
[the remark this answers is not in the document]
Comment (victorlin) [reply package.json:126]: Thanks for making me think about this twice. This is one of a couple solutions, which I'll break down the next comment.

[the remark this answers is not in the document]
Comment (victorlin) [reply package.json:126]: First, note that this is the error without 18c809b968e3b5c1d6f8596e39506dd4ecfeac6d:

```
node_modules/leaflet-gesture-handling/dist/leaflet-gesture-handling.d.ts:1:20 - error TS7016: Could not find a declaration file for module 'leaflet'. 'node_modules/leaflet/dist/leaflet-src.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/leaflet` if it exists or add a new declaration (.d.ts) file containing `declare module 'leaflet';`

1 import * as L from "leaflet";
                     ~~~~~~~~~
```

So, it's actually coming from `leaflet-gesture-handling` which is [used in src/map.js](https://github.com/nextstrain/auspice/blob/1190f88d9a2d3fd5da2830d0449338514b3c33ff/src/components/map/map.js#L6).

The error appears at the intersection of several circumstances:

1. `allowJs` is enabled so that our TS files can import JS files (see 6f449861ab4e7c5ec8cac9855d4ba6f442ab5dd7).
2. `noImplicitAny` is enabled through `strict` mode, meaning variables in all TS files must be typed (even if explicitly `any`).

    - If we convert map.js → map.ts, we will see the error directly [here](https://github.com/nextstrain/auspice/blob/1190f88d9a2d3fd5da2830d0449338514b3c33ff/src/components/map/map.js#LL5C1-L5C1) instead of indirectly from `leaflet-gesture-handling`)

3. `skipLibCheck` is disabled so all declaration files (for Auspice (currently none) and from dependencies) can be checked properly.
4. `leaflet-gesture-handling` has [a TS declaration file](https://github.com/elmarquis/Leaflet.GestureHandling/blob/a53f3713aec5a0d016066796e542ee37c180b50f/dist/leaflet-gesture-handling.d.ts).
5. The `leaflet` package alone does not provide a TS declaration file. `@types/leaflet` provides it separately.
6. For some reason, if a TS declaration file is available for an import in a JS file, the TypeScript compiler will use it, even though it's a JS file which shouldn't rely on types.

[the remark this answers is not in the document]
Comment (victorlin) [reply package.json:126]: Possible solutions and non-solutions based on each point:

1. (non-solution) Disable `allowJs` - this will get rid of the `leaflet-gesture-handling` error but bring forth many other errors due to not having type declarations for all the JS files imported in the converted TS files (due to `noImplicitAny` being enabled).
2. Disable `noImplicitAny` - this will get rid of the error but also hinder TypeScript conversion which relies on surfacing implicit `any` types for proper typing.
3. Enable `skipLibCheck` - this will get rid of the error but also remove the ability to check our own TS declaration files that might come in the future. Ideally there would be an option to skip checking declaration files in `node_modules` alone, but this [isn't currently possible](https://github.com/microsoft/TypeScript/issues/30511).
4. Install @types/leaflet (18c809b968e3b5c1d6f8596e39506dd4ecfeac6d).
5. (non-solution) I don't know of a way to change this behavior.

All are band-aid solutions for an indirect problem. I think (4) is the best long-term option, since we'll need `@types/leaflet` when the map.js → map.ts conversion happens anyways, and it maintains the strictness of TypeScript.

[the remark this answers is not in the document]
Comment (victorlin) [reply package.json:126]: > Why is this necessary, and not types for (say) d3?

This is primarily because of points 4-6. For example, let's take this line:

https://github.com/nextstrain/auspice/blob/1190f88d9a2d3fd5da2830d0449338514b3c33ff/src/components/map/map.js#L12

`d3-selection` does not provide TS declaration files, however map.js is a JS file so it's fine to not have declaration files for imported packages.

If `d3-selection` provided a TS declaration file that then imported something like `d3` whose types are in a separate `@types/d3` package, then we would get an error from the `d3-selection` TS declaration file just like the one above.

Or, if we simply rename `map.js` to `map.ts`, we can see the error on that line looking for `d3-selection`'s missing TS declaration file (which is at [`@types/d3-selection`](https://www.npmjs.com/package/@types/d3-selection)).

[the remark this answers is not in the document]
Comment (jameshadfield) [reply package.json:126]: > The error appears at the intersection of several circumstances:

It sure does! Thanks for the great explanation. Step 6 is a bit unexpected, but I get the general impression that mixed (JS+TS) codebases are not what tsc is optimised for. 

Of the solutions I agree that (5) is the way to go. Would you mind updating the commit message to include your explanation from this thread?

File: .eslintrc.yaml [hunk 7]
```diff
@@ -1,14 +1,17 @@
 ---
 extends:
   - eslint:recommended
+  - plugin:@typescript-eslint/eslint-recommended
```
[the remark this answers is not in the document]
Comment (victorlin) [reply .eslintrc.yaml]: Replaced 568cb9a3d08f806c3758949da8a9c60746e261b5 with 941dce734ce91b9b0afdd2d0fe54d1afc37681e9.

File: package.json (hunk 6 above)
[the remark this answers is not in the document]
Comment (victorlin) [reply package.json:126]: Updated the commit message in 18c809b968e3b5c1d6f8596e39506dd4ecfeac6d → 3f19625468d00d6c29033589c8a703bce01fcc44.

**Review by jameshadfield — COMMENTED** [review]
LGTM 🎉 🙌
